----------------------------------------------------------------------------------------------------
-- Mob death
----------------------------------------------------------------------------------------------------
-- Разработчик: Andrey Fidrya (Zmey) af@svitonline.com
----------------------------------------------------------------------------------------------------

class "mob_death"

function mob_death:__init(obj, storage)
	self.object = obj
	self.st = storage
end

function mob_death:death_callback(victim, who)
	local death = db.storage[victim:id()].death
	if not death then
		death = {}
		db.storage[victim:id()].death = death
	end
	death.killer = (who and who:id()) or -1
	death.killer_name = (who and who:name()) or nil
	xr_logic.try_switch_to_another_section(victim, self.st)
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, storage)
	storage.actions[ mob_death(npc, storage) ] = true
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end
