function false_info()
   if level.name()=="l03u_agr_underground" and db.actor:has_info("yakut_false_start") then db.actor:give_info_portion("yakut_false_have")
elseif level.name()=="l03_agroprom" and db.actor:has_info("yakut_false_have") then
db.actor:give_info_portion("yakut_false_done")
elseif level.name()=="l06_rostok" and db.actor:has_info("zahar_naemnik_start") then
db.actor:give_info_portion("zahar_naemnik_begin")
--elseif level.name()=="l02_garbage" and db.actor:has_info("voen_document_est") then
--db.actor:give_info_portion("bandranen_pda_need")
--elseif level.name()=="l02_garbage" and db.actor:has_info("bandranen_pda_est") then
--db.actor:give_info_portion("fraer_pda_need")
--elseif db.actor:has_info("fraer_pda_est") then db.actor:give_info_portion("prapor_talk_need")
--elseif level.name()=="l07_military" and db.actor:has_info("barrem_talk_est") then
--db.actor:give_info_portion("ara_pda_need")
--elseif level.name()=="l07_military" and db.actor:has_info("ara_pda_est") then
--db.actor:give_info_portion("siv_pda_need")
--elseif db.actor:has_info("siv_pda_est") then db.actor:give_info_portion("sah_talk_need")
elseif level.name()=="l10u_bunker" and db.actor:has_info("ucen_talk_need") then
db.actor:give_info_portion("ucen_talk_spawn")
elseif level.name()=="l01_escape" and db.actor:has_info("prizrak_finalzver_start") then
db.actor:give_info_portion("info_spawn_zver")
end
end


function checking_use_item(obj)
if level.name()=="l10u_bunker" and obj:section()=="sysh_document" then db.actor:give_info_portion("treasure_sysh_have") amk.drop_item(db.actor,obj) amk.remove_item(obj) 
elseif level.name()=="l06_rostok" and obj:section()=="sysh_flash" then db.actor:give_info_portion("treasure_sysh_start") amk.drop_item(db.actor,obj) amk.remove_item(obj)
elseif level.name()=="l01_escape" and obj:section()=="voen_document" then db.actor:give_info_portion("bandranen_pda_need") amk.drop_item(db.actor,obj) amk.remove_item(obj)
--elseif level.name()=="l01_escape" and obj:section()=="wpn_knife" and db.actor:has_info("voen_document_est") then
--db.actor:give_info_portion("bandranen_pda_need")
elseif level.name()=="l02_garbage" and obj:section()=="bandranen_pda" then db.actor:give_info_portion("bandranen_pda_est") amk.drop_item(db.actor,obj) amk.remove_item(obj)
elseif obj:section()=="fraer_pda" and db.actor:has_info("bandranen_pda_est") then db.actor:give_info_portion("prapor_talk_need") amk.drop_item(db.actor,obj) amk.remove_item(obj)
elseif level.name()=="l07_military" and obj:section()=="ara_flash" then db.actor:give_info_portion("ara_pda_est") amk.drop_item(db.actor,obj) amk.remove_item(obj)
elseif obj:section()=="siv_pda" and db.actor:has_info("ara_pda_est") then db.actor:give_info_portion("sah_talk_need") amk.drop_item(db.actor,obj) amk.remove_item(obj)
end
end

local nepis={9613,9622}
local nepis_id={9850,9851}

function dead_npc()
  for a=1,table.getn(nepis),1 do
	local npis=nepis[a]
	local obj=alife():story_object(npis)
	if  obj and IsStalker(obj) and not obj:alive() then
	local name=obj:name()
		if not has_alife_info(name.."_umer") then
			db.actor:give_info_portion(name.."_umer")
		end
	end
	end
--	if	has_alife_info("esc_dan_umer") and not has_alife_info("atak_larger_fail") then
--	db.actor:give_info_portion("atak_larger_fail") 
--	elseif has_alife_info("stalker_green_zahar_umer") and not has_alife_info("atak_larger_fail2") then
--	db.actor:give_info_portion("atak_larger_fail2") 
--	end
end


function main_braad(npc)
npc:set_character_community("ecolog", 0, 0)
npc:set_relation(game_object.friend, db.actor)
db.actor:give_info_portion( "freeman_braad_one" )
end

function setGulagEnemy()
local npc,obj
	
	for i=0,65534 do 
        npc = level.object_by_id(i)
        if npc and npc:name() == "rostok_stalker" then 
            obj = alife():object(npc:id()) 
        end
    end
	alife():create("wpn_mp5",
	obj.position,
	obj.m_level_vertex_id,
	obj.m_game_vertex_id,
	obj.id)
	alife():create("wpn_val",
	obj.position,
	obj.m_level_vertex_id,
	obj.m_game_vertex_id,
	obj.id)
        alife():create_ammo("ammo_5.56x45_ss190",
	obj.position,
	obj.m_level_vertex_id,
	obj.m_game_vertex_id,
	obj.id,
        30)
end

function bloodsucker()
local obj = alife():create("bloodsucker_strong",vector():set(147.087142945,-0.00357154117,59.948166),39508,1228)
local obj = alife():create("bloodsucker_strong",vector():set(147.087142945,-0.00357154117,59.948166),39508,1228)
local obj = alife():create("bloodsucker_strong",vector():set(147.087142945,-0.00357154117,59.948166),39508,1228)
local obj = alife():create("bloodsucker_strong",vector():set(147.087142945,-0.00357154117,59.948166),39508,1228)
local obj = alife():create("bloodsucker_strong",vector():set(147.087142945,-0.00357154117,59.948166),39508,1228)
local obj = alife():create("bloodsucker_strong",vector():set(147.087142945,-0.00357154117,59.948166),39508,1228)
end

function main_friend(npc)
npc:set_relation(game_object.friend, db.actor)
end

function zombie_blow()
local obj = alife():create("zombie_blow",vector():set(-108.36364746,21.564731597,-35.483924865),312,1529)
local obj = alife():create("zombie_blow",vector():set(-108.36364746,21.564731597,-35.483924865),312,1529)
local obj = alife():create("zombie_blow",vector():set(-108.36364746,21.564731597,-35.483924865),312,1529)
local obj = alife():create("zombie_blow",vector():set(-91.32671356,21.57417869,-23.8667068),741,1529)
local obj = alife():create("zombie_blow",vector():set(-91.32671356,21.57417869,-23.8667068),741,1529)
local obj = alife():create("zombie_blow",vector():set(-91.32671356,21.57417869,-23.8667068),741,1529)
local obj = alife():create("zombie_blow",vector():set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
local obj = alife():create("zombie_blow",vector():set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
local obj = alife():create("zombie_blow",vector():set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
local obj = alife():create("zombie_blow",vector():set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
local obj = alife():create("zombie_blow",vector():set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
local obj = alife():create("zombie_blow",vector():set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
local obj = alife():create("zombie_blow",vector():set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
local obj = alife():create("zombie_blow",vector():set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
local obj = alife():create("zombie_blow",vector():set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
local obj = alife():create("zombie_blow",vector():set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
local obj = alife():create("zombie_blow",vector():set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
local obj = alife():create("zombie_blow",vector():set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
end

function zasada_for()
local obj = alife():create("electro_chimera",vector():set(12.886095046997,-16.55083847,175.3548889),320050,1697)
local obj = alife():create("electro_chimera",vector():set(12.886095046997,-16.55083847,175.3548889),320050,1697)
local obj = alife():create("electro_chimera",vector():set(12.886095046997,-16.55083847,175.3548889),320050,1697)
local obj = alife():create("electro_chimera",vector():set(12.886095046997,-16.55083847,175.3548889),320050,1697)
end

function radar_man()
local obj = alife():create("m_controller_old",vector():set(-61.979244232178,-21.8962020874,35.8896102905),195,2727)
local obj = alife():create("m_controller_old",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
local obj = alife():create("zombie_blow",vector():set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
end

function killactor (sid)
local npc = level_object_by_sid (9623)
    if npc == nil or npc:alive () == false then
       return 
    end    
    npc:set_relation (game_object.enemy, db.actor)
local npc = level_object_by_sid (9624)
    if npc == nil or npc:alive () == false then
       return 
    end    
    npc:set_relation (game_object.enemy, db.actor)
local npc = level_object_by_sid (9625)
    if npc == nil or npc:alive () == false then
       return 
    end    
    npc:set_relation (game_object.enemy, db.actor)
local npc = level_object_by_sid (9905)
    if npc == nil or npc:alive () == false then
       return 
    end    
    npc:set_relation (game_object.enemy, db.actor)	
end

function killactor_spawn()
local obj = alife():create("killer_boevik2",vector():set(43.09783554,-8.13079166,14.410468),345215,1582)
local obj = alife():create("killer_boevik1",vector():set(59.50757599,-8.5839643,9.3478708),358211,1570)
local obj = alife():create("killer_boevik3",vector():set(59.52076721,-8.7670116,22.850177765),358227,1559)
local obj = alife():create("killer_boevik4",vector():set(40.780555725,-8.319325447,19.2897949),343015,1582)
local obj = alife():create("killer_boevik5",vector():set(46.9849434,-8.1420059,20.492004),348191,1582)
local obj = alife():create("killer_boevik6",vector():set(51.40478897,-8.08700466,13.5054283),351374,1582)
end

function sorok_pda()
	return new_dialog.item_much("device_pda_npc",40) ~= false
end
   
   
function sorok_pda_sdal(first_speaker, second_speaker)
new_dialog.out_item_much("device_pda_npc",40) 
end

function chern_dogs()
local obj = alife():create("psy_dog_radar",vector():set(338.74279785,-46.47824478,-163.8179168),86443,2086)
local obj = alife():create("psy_dog_radar",vector():set(338.74279785,-46.47824478,-163.8179168),86443,2086)
local obj = alife():create("psy_dog_radar",vector():set(354.486083984,-45.66619491577,-213.2041015625),95066,1872)
local obj = alife():create("psy_dog_radar",vector():set(354.486083984,-45.66619491577,-213.2041015625),95066,1872)
end

function create_monstr()
local position = db.actor:position()
	position.x = position.x + 13
local obj = alife():create("burer_strong",
			position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
local obj = alife():create("burer_strong",
			position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end			
			
function kill_npc(sid)
local npc = level_object_by_sid (9630)
    if npc == nil or npc:alive () == false then
       return 
    end    
    npc:kill(npc)
end


function take_yakut_agro2_spot()
	sak.add_spot_of_docent(9650)
end


function new_comp()
local obj = alife():create("computer_new",vector():set(27.945556640625,-6.619695186615,-14.894629478455),6746,1140)
end

function release_actor_items()
    -- вещи исключения
    local items = {
        ["af_blood_tutorial"] = true,
        ["new_book"] = true,
        ["diplomat"] = true,
		["repair_box_outfit"] = true,
        ["computer"] = true,
        ["quest_case_01"] = true,
		["inventory_sakbox_01"] = true,
        ["inventory_sakbox_02"] = true,
        ["inventory_sakbox_03"] = true,
		["inventory_sakbox_04"] = true,
        ["inventory_sakbox_05"] = true,
        ["sak_book1"] = true,
		["sak_book2"] = true,
        ["sak_book3"] = true,
        ["stukach_book"] = true,
		["sak_book4"] = true,
        ["playboy"] = true,
		["playboy10"] = true,
		["sak_plan"] = true,
        ["quest_case_05"] = true,
        ["quest_case_06"] = true,
		["quest_manycase_01"] = true,
        ["dynamite"] = true,
        ["esc_wounded_flash"] = true,
		["decoder1"] = true,
        ["gunslinger_flash"] = true,
        ["quest_case_02"] = true,
		["val_key_to_underground"] = true,
        ["bar_tiran_pda"] = true,
        ["garbage_pda"] = true,
		["pda_krysyka"] = true,
        ["device_pda_npc"] = true,
		["agroprom_pda"] = true,
		["und_pda"] = true,
        ["rad_pda"] = true,
        ["strelok_pda"] = true,
		["scaintist_pda"] = true,
        ["bar_lucky_pda"] = true,
        ["bar_ecolog_flash"] = true,
		["lab_x16_documents"] = true,
        ["pda_priz"] = true,
        ["scaintist_docs"] = true,
		["case_freeman"] = true,
        ["lab_x10_documents"] = true,
        ["bland_flash"] = true,
		["good_psy_helmet"] = true,
        ["bad_psy_helmet"] = true,
		["kruglov_flash"] = true,
		["crazy_flash"] = true,
        ["sak_resiver"] = true,
        ["sak_resiver_yantar"] = true,
		["mil_svoboda_leader_pda"] = true,
        ["dar_pass_flash"] = true,
        ["dar_pass_document"] = true,
		["dar_document1"] = true,
        ["dar_document2"] = true,
        ["dar_document3"] = true,
		["dar_document4"] = true,
        ["dar_document5"] = true,
        ["sak_document"] = true,
		["sak_document2"] = true,
        ["rad_document6"] = true,
		["rad_document7"] = true,
		["pri_decoder_documents"] = true,
        ["cit_doctors_key"] = true,
        ["decoder"] = true,
		["amk_af_night_star"] = true,
        ["flame_parts"] = true,
        ["gorelka"] = true,
		["manometr"] = true,
        ["trubka"] = true,
        ["flamethrower_bad"] = true,
		["matras"] = true,
		["wpn_binoc"] = true,
		["stalker_outfit_m3"] = true,
		["wpn_mp5_m1"] = true,
		["device_pda"] = true,
		["notebook_new"] = true,
		["notebook"] = true,
		["sysh_document"] = true,
        ["sysh_flash"] = true,
		["new_document_sniper"] = true,
		["inventory_new_box"] = true,
		["sniper_flash"] = true,
		["new_book_prizrak"] = true,
		["computer_new"] = true,
		["nauch_flash"] = true,
		["wpn_knife"] = true,
		["device_torch"] = true,
		["wpn_flame"] = true}
    local obj
    local sim = alife()
    local actor = db.actor;
    -- перебор вещей инвентаря
    local cnt = actor:object_count()
    for i=0, cnt-1 do
        obj = actor:object(i)
        if not items[obj:section()] then
            -- удаление вещи
			--amk.start_timer(math.random(20,30))
            sim:release(sim:object(obj:id()), true)
		sleep_manager.main(5+amk.load_variable("gg_need_sleep_nrg",0))
			--sak.add_new_military()
        end
    end
end	

function release_actor_money()
  local num = db.actor:money() 
  db.actor:give_money(-num)
  game_stats.money_quest_update(-num) 
end

function friendactor(community1, community2)
relation_registry.set_community_goodwill ("stalker", "actor", 2000)
end

function atak_larger_have(task, info)
  if db.actor and db.actor:has_info("snip_esc1_dead") and db.actor:has_info("snip_esc2_dead") and db.actor:has_info("snip_esc3_dead") and db.actor:has_info("snip_esc4_dead") and db.actor:has_info("snip_esc5_dead") and db.actor:has_info("snip_esc6_dead")and db.actor:has_info("snip_esc7_dead") and db.actor:has_info("snip_esc8_dead") and db.actor:has_info("snip_esc9_dead") and db.actor:has_info("snip_esc10_dead") and db.actor:has_info("snip_esc11_dead") and db.actor:has_info("snip_esc12_dead") ~= nil then
  return db.actor:give_info_portion("atak_larger_have") ~= nil   
  end
return false
end

function zahar_naemnik_have(task, info)
  if db.actor and db.actor:has_info("naem_zahar1_dead") and db.actor:has_info("naem_zahar2_dead") and db.actor:has_info("naem_zahar3_dead") and db.actor:has_info("naem_zahar4_dead") and db.actor:has_info("naem_zahar5_dead") and db.actor:has_info("naem_zahar6_dead") ~= nil then
  return db.actor:give_info_portion("zahar_naemnik_have") ~= nil   
  end
return false
end

function check_npc_dead()
    if db.actor and db.actor:has_info("esc_dan_umer") and db.actor:has_info("informator_pda_start") and not db.actor:has_info("informator_pda_have") and not db.actor:has_info("informator_pda_done") and not db.actor:has_info("esc_dan_umer_newsinfo1") then
                amk.start_timer("sms_new",math.random(30,60))
               db.actor:give_info_portion("esc_dan_umer_newsinfo1")  
	end
	if db.actor and db.actor:has_info("esc_dan_umer") and db.actor:has_info("dan_grab_start") and  db.actor:has_info("dan_grab_have") and not db.actor:has_info("dan_grab_done") and not db.actor:has_info("esc_dan_umer_newsinfo2") then
                amk.start_timer("sms_new",math.random(40,70))
               db.actor:give_info_portion("esc_dan_umer_newsinfo2")
	end
    if db.actor and db.actor:has_info("esc_dan_umer") and db.actor:has_info("dan_flash_start") and  db.actor:has_info("dan_flash_have")  and not db.actor:has_info("dan_flash_done") and not db.actor:has_info("esc_dan_umer_newsinfo3") then
                amk.start_timer("sms_new",math.random(40,70))
               db.actor:give_info_portion("esc_dan_umer_newsinfo3")
	end		
end

function sms_new()
    db.actor:give_info_portion("sms_new_dan1")
                amk.send_tip(game.translate_string("sms_new_dan1_text"),nil,nil,30)
end

function check_ecolog_dead()
    if db.actor and db.actor:has_info("ucen_talk_est") and not db.actor:has_info("esc_dan_umer_newsinfo4") then
                amk.start_timer("sms_new1",math.random(140,170))
               db.actor:give_info_portion("esc_dan_umer_newsinfo4")
	end		
end

function sms_new1()
    db.actor:give_info_portion("sms_new_dan2")
                amk.send_tip(game.translate_string("sms_new_dan2_text"),nil,nil,30)
end

function actor_has_money_30000()
  return db.actor:money()>=30000
end

function give_money_30000(t1,t2)
  local npc=t1
  if npc:id()==db.actor:id() then
    npc=t2
  end
  dialogs.relocate_money(npc,30000,"out")
end

function delete_smart()
  local se_obj = alife():object("esc2_bloodsucker1")
  if se_obj then
    alife():release(se_obj, true)
  end
  local se_obj = alife():object("ros_smart_stalker1")
  if se_obj then
    alife():release(se_obj, true)
  end
end


