local math_random = math.random

local falses = {
	l01_escape = {
		has	= "prizrak_finalzver_start",
		give	= "info_spawn_zver"
	},
	l03_agroprom = {
		has	= "yakut_false_have",
		give	= "yakut_false_done"
	},
	l03u_agr_underground = {
		has	= "yakut_false_start",
		give	= "yakut_false_have"
	},
	l06_rostok = {
		has	= "zahar_naemnik_start",
		give	= "zahar_naemnik_begin"
	},
	l10u_bunker = {
		has	= "ucen_talk_need",
		give	= "ucen_talk_spawn"
	}
}

function false_info()
	local entry = falses[level.name()]
	if entry and not has_info(entry.give) and has_info(entry.has) then
		Actor:give_info_portion(entry.give)
	end
end

local items = {
	l01_escape = {
		item	= "voen_document",
		info	= "bandranen_pda_need"
	},
	l02_garbage = {
		item	= "bandranen_pda",
		info	= "bandranen_pda_est"
	},
	l06_rostok = {
		item	= "sysh_flash",
		info	= "treasure_sysh_start"
	},
	l07_military = {
		item	= "ara_flash",
		info	= "ara_pda_est"
	},
	l10u_bunker = {
		item	= "sysh_document",
		info	= "treasure_sysh_have"
	}
}

local always_items = {
	fraer_pda = {
		has	= "bandranen_pda_est",
		give	= "prapor_talk_need"
	},
	siv_pda = {
		has	= "ara_pda_est",
		give	= "sah_talk_need"
	}
}

function checking_use_item(obj)
	local sect = obj:section()

	local entry = always_items[sect]
	if entry then
		if has_info(entry.has) then Actor:give_info_portion(entry.give) end
		return
	end

	local entry = items[level.name()]
	if entry and sect == entry.item then Actor:give_info_portion(entry.info) end
end

local nepis = {
	9613,	-- Захар
	9622	-- Дэн
}

function dead_npc()
	for a=1, #nepis do
		local obj = AI:story_object(nepis[a])
		if obj and obj:is_stalker() and not obj:alive() then
			local info = obj:name() .. "_umer"
			if not has_alife_info(info) then
				Actor:give_info_portion(info)
			end
		end
	end
end

function main_braad(npc)
npc:set_character_community("ecolog", 0, 0)
npc:set_relation(game_object.friend, Actor)
Actor:give_info_portion( "freeman_braad_one" )
end

function setGulagEnemy()
	local obj = server_object("rostok_stalker")
	if not obj then return end

	for _, sect in ipairs({
		"wpn_mp5", "wpn_val", "ammo_9x19_pbp",
		"ammo_9x39_pab9", "ammo_5.56x45_ss190"
	}) do
		create_random(sect, obj.position, obj.m_level_vertex_id,
			      obj.m_game_vertex_id, obj.id)
	end
end

function bloodsucker()
	local v = vector()
	AI:create("bloodsucker_strong",v:set(147.087142945,-0.00357154117,59.948166),39508,1228)
	AI:create("bloodsucker_strong",v:set(147.087142945,-0.00357154117,59.948166),39508,1228)
	AI:create("bloodsucker_strong",v:set(147.087142945,-0.00357154117,59.948166),39508,1228)
	AI:create("bloodsucker_strong",v:set(147.087142945,-0.00357154117,59.948166),39508,1228)
	AI:create("bloodsucker_strong",v:set(147.087142945,-0.00357154117,59.948166),39508,1228)
	AI:create("bloodsucker_strong",v:set(147.087142945,-0.00357154117,59.948166),39508,1228)
end

function main_friend(npc)
npc:set_relation(game_object.friend, Actor)
end

function zombie_blow()
	local v = vector()
	AI:create("zombie_blow",v:set(-108.36364746,21.564731597,-35.483924865),312,1529)
	AI:create("zombie_blow",v:set(-108.36364746,21.564731597,-35.483924865),312,1529)
	AI:create("zombie_blow",v:set(-108.36364746,21.564731597,-35.483924865),312,1529)
	AI:create("zombie_blow",v:set(-91.32671356,21.57417869,-23.8667068),741,1529)
	AI:create("zombie_blow",v:set(-91.32671356,21.57417869,-23.8667068),741,1529)
	AI:create("zombie_blow",v:set(-91.32671356,21.57417869,-23.8667068),741,1529)
	AI:create("zombie_blow",v:set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
	AI:create("zombie_blow",v:set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
	AI:create("zombie_blow",v:set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
	AI:create("zombie_blow",v:set(-146.986175537,-19.0885162,-72.52413177),1082,1457)
	AI:create("zombie_blow",v:set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
	AI:create("zombie_blow",v:set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
	AI:create("zombie_blow",v:set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
	AI:create("zombie_blow",v:set(-85.37963104248,-19.090393066,-49.233089447),9988,1495)
	AI:create("zombie_blow",v:set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
	AI:create("zombie_blow",v:set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
	AI:create("zombie_blow",v:set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
	AI:create("zombie_blow",v:set(-86.6029510498,-19.0902767,-171.46553039551),9340,1455)
end

function zasada_for()
	local v = vector()
	AI:create("electro_chimera",v:set(12.886095046997,-16.55083847,175.3548889),320050,1697)
	AI:create("electro_chimera",v:set(12.886095046997,-16.55083847,175.3548889),320050,1697)
	AI:create("electro_chimera",v:set(12.886095046997,-16.55083847,175.3548889),320050,1697)
	AI:create("electro_chimera",v:set(12.886095046997,-16.55083847,175.3548889),320050,1697)
end

function radar_man()
	local v = vector()
	AI:create("m_controller_old",v:set(-61.979244232178,-21.8962020874,35.8896102905),195,2727)
	AI:create("m_controller_old",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	AI:create("zombie_blow",v:set(0.86928582191467,-23.69577599,1.777916193),6155,2703)
end

function killactor (sid)
local npc = level_object_by_sid (9623)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, Actor)
local npc = level_object_by_sid (9624)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, Actor)
local npc = level_object_by_sid (9625)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, Actor)
local npc = level_object_by_sid (9905)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, Actor)
end

function killactor_spawn()
	local v = vector()
	AI:create("killer_boevik2",v:set(43.09783554,-8.13079166,14.410468),345215,1582)
	AI:create("killer_boevik1",v:set(59.50757599,-8.5839643,9.3478708),358211,1570)
	AI:create("killer_boevik3",v:set(59.52076721,-8.7670116,22.850177765),358227,1559)
	AI:create("killer_boevik4",v:set(40.780555725,-8.319325447,19.2897949),343015,1582)
	AI:create("killer_boevik5",v:set(46.9849434,-8.1420059,20.492004),348191,1582)
	AI:create("killer_boevik6",v:set(51.40478897,-8.08700466,13.5054283),351374,1582)
end

function sorok_pda()
	return has("device_pda_npc", 40)
end

function sorok_pda_sdal(first_speaker, second_speaker)
	lost("device_pda_npc", 40)
end

function chern_dogs()
	local v = vector()
	AI:create("psy_dog_radar",v:set(338.74279785,-46.47824478,-163.8179168),86443,2086)
	AI:create("psy_dog_radar",v:set(338.74279785,-46.47824478,-163.8179168),86443,2086)
	AI:create("psy_dog_radar",v:set(354.486083984,-45.66619491577,-213.2041015625),95066,1872)
	AI:create("psy_dog_radar",v:set(354.486083984,-45.66619491577,-213.2041015625),95066,1872)
end

function create_monstr()
local position = Actor:position()
	position.x = position.x + 13
	AI:create("burer_strong", position, Actor:level_vertex_id(), Actor:game_vertex_id())
	AI:create("burer_strong", position, Actor:level_vertex_id(), Actor:game_vertex_id())
end

function kill_npc(sid)
local npc = level_object_by_sid (9630)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:kill(npc)
end

function take_yakut_agro2_spot()
	sak.add_spot_of_docent(9650)
end

function new_comp()
	AI:create("computer_new",vector():set(27.945556640625,-6.619695186615,-14.894629478455),6746,1140)
end

-- вещи исключения
local items = {
        ["af_blood_tutorial"] = true,
        ["new_book"] = true,
        ["diplomat"] = true,
		["repair_box_outfit"] = true,
        ["computer"] = true,
        ["quest_case_01"] = true,
		["inventory_sakbox_01"] = true,
        ["inventory_sakbox_02"] = true,
        ["inventory_sakbox_03"] = true,
		["inventory_sakbox_04"] = true,
        ["inventory_sakbox_05"] = true,
        ["sak_book1"] = true,
		["sak_book2"] = true,
        ["sak_book3"] = true,
        ["stukach_book"] = true,
		["sak_book4"] = true,
        ["playboy"] = true,
		["playboy10"] = true,
		["sak_plan"] = true,
        ["quest_case_05"] = true,
        ["quest_case_06"] = true,
		["quest_manycase_01"] = true,
        ["dynamite"] = true,
        ["esc_wounded_flash"] = true,
		["decoder1"] = true,
        ["gunslinger_flash"] = true,
        ["quest_case_02"] = true,
		["val_key_to_underground"] = true,
        ["bar_tiran_pda"] = true,
        ["garbage_pda"] = true,
		["pda_krysyka"] = true,
        ["device_pda_npc"] = true,
		["agroprom_pda"] = true,
		["und_pda"] = true,
        ["rad_pda"] = true,
        ["strelok_pda"] = true,
		["scaintist_pda"] = true,
        ["bar_lucky_pda"] = true,
        ["bar_ecolog_flash"] = true,
		["lab_x16_documents"] = true,
        ["pda_priz"] = true,
        ["scaintist_docs"] = true,
		["case_freeman"] = true,
        ["lab_x10_documents"] = true,
        ["bland_flash"] = true,
		["good_psy_helmet"] = true,
        ["bad_psy_helmet"] = true,
		["kruglov_flash"] = true,
		["crazy_flash"] = true,
        ["sak_resiver"] = true,
        ["sak_resiver_yantar"] = true,
		["mil_svoboda_leader_pda"] = true,
        ["dar_pass_flash"] = true,
        ["dar_pass_document"] = true,
		["dar_document1"] = true,
        ["dar_document2"] = true,
        ["dar_document3"] = true,
		["dar_document4"] = true,
        ["dar_document5"] = true,
        ["sak_document"] = true,
		["sak_document2"] = true,
        ["rad_document6"] = true,
		["rad_document7"] = true,
		["pri_decoder_documents"] = true,
        ["cit_doctors_key"] = true,
        ["decoder"] = true,
		["amk_af_night_star"] = true,
        ["flame_parts"] = true,
        ["gorelka"] = true,
		["manometr"] = true,
        ["trubka"] = true,
        ["flamethrower_bad"] = true,
		["matras"] = true,
		["wpn_binoc"] = true,
		["stalker_outfit_m3"] = true,
	wpn_mp5_sk2_m1			= true,
		["device_pda"] = true,
		["notebook_new"] = true,
		["notebook"] = true,
		["sysh_document"] = true,
        ["sysh_flash"] = true,
		["new_document_sniper"] = true,
		["inventory_new_box"] = true,
		["sniper_flash"] = true,
		["new_book_prizrak"] = true,
		["computer_new"] = true,
		["nauch_flash"] = true,
		["wpn_knife"] = true,
		["device_torch"] = true,
		["wpn_flame"] = true,
	["amk_transmutator"]		= true,
	arhara_listok			= true,
	arhara_obman1			= true,
	arhara_obman2			= true,
	arhara_obman3			= true,
	arhara_obman4			= true,
	arhara_obman5			= true,
	arhara_tele			= true
}

function release_actor_items()
    local obj
    local actor = Actor
    -- перебор вещей инвентаря
    local cnt = actor:object_count()
    for i=0, cnt-1 do
        obj = actor:object(i)
        if not items[obj:section()] then
            -- удаление вещи
            AI:release(AI:object(obj:id()), true)
		Dream:sleep(5+amk.load_variable("gg_need_sleep_nrg",0))
        end
    end
end

function release_actor_money()
  local num = Actor:money()
  Actor:give_money(-num)
end

function friendactor(community1, community2)
relation_registry.set_community_goodwill ("stalker", "actor", 2000)
end

function atak_larger_have(task, info)
	local actor = Actor
	if actor and
	   actor:has_info("snip_esc1_dead") and
	   actor:has_info("snip_esc2_dead") and
	   actor:has_info("snip_esc3_dead") and
	   actor:has_info("snip_esc4_dead") and
	   actor:has_info("snip_esc5_dead") and
	   actor:has_info("snip_esc6_dead")and
	   actor:has_info("snip_esc7_dead") and
	   actor:has_info("snip_esc8_dead") and
	   actor:has_info("snip_esc9_dead") and
	   actor:has_info("snip_esc10_dead") and
	   actor:has_info("snip_esc11_dead") and
	   actor:has_info("snip_esc12_dead") ~= nil then
		return actor:give_info_portion("atak_larger_have") ~= nil
	end
	return false
end

function zahar_naemnik_have(task, info)
	local actor = Actor
	if actor and
	   actor:has_info("naem_zahar1_dead") and
	   actor:has_info("naem_zahar2_dead") and
	   actor:has_info("naem_zahar3_dead") and
	   actor:has_info("naem_zahar4_dead") and
	   actor:has_info("naem_zahar5_dead") and
	   actor:has_info("naem_zahar6_dead") ~= nil then
		return actor:give_info_portion("zahar_naemnik_have") ~= nil
	end
	return false
end

function check_npc_dead()
	local actor = Actor
    if actor and actor:has_info("esc_dan_umer") and actor:has_info("informator_pda_start") and not actor:has_info("informator_pda_have") and not actor:has_info("informator_pda_done") and not actor:has_info("esc_dan_umer_newsinfo1") then
                amk.start_timer("sms_new",math_random(30,60))
               actor:give_info_portion("esc_dan_umer_newsinfo1")
	end
	if actor and actor:has_info("esc_dan_umer") and actor:has_info("dan_grab_start") and  actor:has_info("dan_grab_have") and not actor:has_info("dan_grab_done") and not actor:has_info("esc_dan_umer_newsinfo2") then
                amk.start_timer("sms_new",math_random(40,70))
               actor:give_info_portion("esc_dan_umer_newsinfo2")
	end
    if actor and actor:has_info("esc_dan_umer") and actor:has_info("dan_flash_start") and  actor:has_info("dan_flash_have")  and not actor:has_info("dan_flash_done") and not actor:has_info("esc_dan_umer_newsinfo3") then
                amk.start_timer("sms_new",math_random(40,70))
               actor:give_info_portion("esc_dan_umer_newsinfo3")
	end
end

function sms_new()
    Actor:give_info_portion("sms_new_dan1")
                amk.send_tip(game.translate_string("sms_new_dan1_text"),nil,nil,30)
end

function check_ecolog_dead()
	local actor = Actor
    if actor and actor:has_info("ucen_talk_est") and not actor:has_info("esc_dan_umer_newsinfo4") then
                amk.start_timer("sms_new1",math_random(140,170))
               actor:give_info_portion("esc_dan_umer_newsinfo4")
	end
end

function sms_new1()
    Actor:give_info_portion("sms_new_dan2")
                amk.send_tip(game.translate_string("sms_new_dan2_text"),nil,nil,30)
end

function actor_has_money_30000()
	return has_money(30000)
end

function give_money_30000()
	lost_money(30000)
end

function delete_smart()
  local se_obj = AI:object("esc2_bloodsucker1")
  if se_obj then
    AI:release(se_obj, true)
  end
  local se_obj = AI:object("ros_smart_stalker1")
  if se_obj then
    AI:release(se_obj, true)
  end
end
