-- Типы схем:
stype_stalker    = 0
stype_mobile     = 1
stype_item       = 2
stype_heli       = 3
stype_restrictor = 4

----------------------------------------------------------------------
-- Загрузка схем:
----------------------------------------------------------------------

local toload = {
----------------------------------------------------------------------
-- Загрузка модулей сталкеров:
----------------------------------------------------------------------

	-- AMK
	{ "watcher_act", "watcher_act", stype_stalker, "xr_", "" },
	{ "blowout_scheme", "blowout_scheme" },

	-- Vanilla
	"danger", "abuse", "walker", "remark", "sleeper", "kamp", "camper",
	"meet", "heli_hunter",

	{ "xr_attendant", "follower" },

	"combat", "death", "use", "hit", "wounded", "combat_ignore", "patrol",

	-- AI Pack
	{ "xrs_grenade", "grenadier" },
	{ "xrs_medic", "medic" },
	{ "xrs_armor", "pick_armor" },

----------------------------------------------------------------------
-- Загрузка модулей монстров:
----------------------------------------------------------------------

	{ "mob_walker", "mob_walker", stype_mobile, "mob_" },

	"combat", "death", "trade", "jump", "camp", "home", "trader",

----------------------------------------------------------------------
-- Загрузка модулей физических объектов:
----------------------------------------------------------------------

	{ "ph_door", "ph_door", stype_item, "ph_" },

	"gate", "idle", "on_hit", "car", "button", "code", "sound",

	{ "ph_appforce", "ph_force" },
	{ "ph_death", "ph_on_death" },

	"oscillate",

----------------------------------------------------------------------
-- Загрузка модулей вертолёта:
----------------------------------------------------------------------

	{ "heli_move", "heli_move", stype_heli },

----------------------------------------------------------------------
-- Загрузка модулей рестрикторов:
----------------------------------------------------------------------

	-- Vanilla
	{ "sr_tip", "sr_tip", stype_restrictor, "sr_" },

	"teleport", "sound", "idle", "territory", "danger", "light", "particle",

	{ "sr_sound2d", "sr_sound_act" },

	"timer", "psy_antenna", "aes_deadzone", "cutscene",

	-- OGSM
	{ "ogsm_effector", "ogsm_effector" }
}

local file, scheme, stype, file_pfx, scheme_pfx
for _, iter in ipairs(toload) do
	if type(iter) == "table" then
		file = iter[1]
		scheme = iter[2]

		if iter[3] then
			stype = iter[3]
			file_pfx = iter[4]
			scheme_pfx = iter[5] or file_pfx
		end
	else
		file = file_pfx .. iter
		scheme = scheme_pfx .. iter
	end

	load_scheme(file, scheme, stype)
end

toload, file, scheme, stype, file_pfx, scheme_pfx = nil, nil, nil, nil, nil, nil
