----------------------------------------------------------------------------------------------------
-- Physics death checker
----------------------------------------------------------------------------------------------------
-- Разработчик: Tunduk Vladimir aka Sidorovich
----------------------------------------------------------------------------------------------------

class "ph_on_death"

function ph_on_death:__init(obj, storage)
	self.object = obj
	self.st = storage
end

function ph_on_death:reset_scheme()
end

function ph_on_death:update(delta)
end

function ph_on_death:death_callback (obj, who)
	if db.storage[self.object:id()].active_scheme then
		xr_logic.try_switch_to_another_section (obj, self.st, db_actor)
	end
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder_q(npc, storage)
	storage.actions[ph_on_death(npc, storage)] = true
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end

function disable_scheme(npc, scheme)
end
