--[[-----------------------------------------------------------------------------------------------
 File         : sa_callbacks.script
 Description  : Библиотека колбеков
 Copyright    : Shadows Addon
 Author       : Ray Twitty aka Shadows
 Date         : 06.11.2012
 Last edit    : 12.11.2018
--]]-----------------------------------------------------------------------------------------------
prefetch("sa_utils")
--[[-----------------------------------------------------------------------------------------------
 * ACTOR
--]]-----------------------------------------------------------------------------------------------
local hud_animations_mgr
local hud_interface_mgr
local next_500 = 0
---------------------------------------------------------------------------------------------------
function actor_update(delta)
	if not hud_animations_mgr then
		hud_animations_mgr = sa_hud_animations_mgr.get_hud_animations_mgr()
		hud_interface_mgr = sa_hud_interface_mgr.get_hud_interface_mgr()
	end
	hud_animations_mgr:update()
	hud_interface_mgr:update()
	sa_inventory_items_mgr.repack_ammo()
	if next_500 < time_real_ms then
		sa_main.bunker_cooling_sound()
		next_500 = time_real_ms + 500
	end
	sa_main.scope_zoom_mode_callback()
	reap.update()
end
---------------------------------------------------------------------------------------------------
function actor_net_spawn()
	sa_main.disable_ui_info()
	reap.net_spawn()
end
---------------------------------------------------------------------------------------------------
function actor_net_destroy()
	hud_animations_mgr:clear_scope_texture()
end
---------------------------------------------------------------------------------------------------
local last_health
---------------------------------------------------------------------------------------------------
function actor_hit(obj, amount, local_direction, who, bone_index)
	if last_health then
		reap.hit_effectors(last_health - Actor.health)
	end
	last_health = nil
end
---------------------------------------------------------------------------------------------------
function actor_death(victim, who)
	hud_interface_mgr:actor_death()
	sa_main.restore_torch(victim)
	reap.actor_death(victim, who)
end
---------------------------------------------------------------------------------------------------
function item_take(obj)
	reap.item_take(obj)
	if device().precache_frame == 0 then
		sa_inventory_items_mgr.artefacts_statistic(obj)
	end
end
---------------------------------------------------------------------------------------------------
local belt_obj_by_id = {}
---------------------------------------------------------------------------------------------------
function item_drop(obj)
	reap.item_drop(obj)
	if belt_obj_by_id[obj:id()] then
		item_drop_from_belt(obj)
		belt_obj_by_id[obj:id()] = nil
	end
end
---------------------------------------------------------------------------------------------------
function item_drop_from_belt(obj)
	sa_inventory_items_mgr.update_artefacts_belt_lock(obj)
	reap.item_drop_from_belt(obj)
end
---------------------------------------------------------------------------------------------------
function item_use(obj)
	reap.item_use(obj)
end
---------------------------------------------------------------------------------------------------
function item_belt(obj)
	sa_inventory_items_mgr.update_artefacts_belt_lock(obj)
	if Actor:belt_count() > 1 then
		sa_inventory_items_mgr.check_ammo(obj)
	end
	reap.item_belt(obj)
	belt_obj_by_id[obj:id()] = obj
end
---------------------------------------------------------------------------------------------------
function item_move_from_belt(obj)
	reap.item_move_from_belt(obj)
end
---------------------------------------------------------------------------------------------------
function item_ruck(obj)
	sa_inventory_items_mgr.update_artefacts_belt_lock(obj)
	if Actor:ruck_count() > 1 then
		sa_inventory_items_mgr.check_ammo(obj)
	end
	reap.item_ruck(obj)
	if belt_obj_by_id[obj:id()] then
		item_move_from_belt(obj)
		belt_obj_by_id[obj:id()] = nil
	end
end
---------------------------------------------------------------------------------------------------
function item_slot(obj)
	reap.item_slot(obj)
	if belt_obj_by_id[obj:id()] then
		item_move_from_belt(obj)
		belt_obj_by_id[obj:id()] = nil
	end
end
---------------------------------------------------------------------------------------------------
function take_item_from_box(box, item)
	reap.take_item_from_box(box, item)
end
---------------------------------------------------------------------------------------------------
function info(info_id, ui_info)
	if ui_info then
		sa_main.dead_body_sounds(info_id)
	end
	reap.info(info_id, ui_info)
end
---------------------------------------------------------------------------------------------------
function scope_zoom_mode(mode_on)
	if not level.main_input_receiver() then
		if mode_on then
			level.hide_indicators()
		else
			level.show_indicators()
		end
	end
end
---------------------------------------------------------------------------------------------------
function hit_effector()
	if not last_health then
		last_health = Actor.health
	end
end
---------------------------------------------------------------------------------------------------
function key_press(dik)
	if not level.main_input_receiver() then
		sa_main.pda_info_fix(dik)
	end
	if hud_animations_mgr then
		hud_animations_mgr:on_keyboard(dik, key_events.pressed)
	end
	pressed_keys[dik] = true
end
---------------------------------------------------------------------------------------------------
function key_release(dik)
	if hud_animations_mgr then
		hud_animations_mgr:on_keyboard(dik, key_events.released)
	end
	pressed_keys[dik] = nil
end
---------------------------------------------------------------------------------------------------
function new_game()
	timer("sa_main.yantar_psy_blowout", math.random(5 * 60 * 1000, 7 * 60 * 1000), true)
	reap.new_game()
end
---------------------------------------------------------------------------------------------------
function actor_save(packet)
	reap.actor_save(packet)
end
---------------------------------------------------------------------------------------------------
function actor_load(reader)
	reap.actor_load(reader)
end
--[[-----------------------------------------------------------------------------------------------
 * NPC
--]]-----------------------------------------------------------------------------------------------
function npc_use(obj, who)
	if not (obj:alive() or is_key_pressed(bind_to_dik(key_bindings.kACCEL))) then
		Actor:give_info_portion("ui_dead_body")
	end
end
---------------------------------------------------------------------------------------------------
function npc_death(victim, who)
	sa_main.restore_torch(victim)
end
--[[-----------------------------------------------------------------------------------------------
 * MONSTER
--]]-----------------------------------------------------------------------------------------------
function monster_use(obj, who)
	if not (obj:alive() or is_key_pressed(bind_to_dik(key_bindings.kACCEL))) then
		Actor:give_info_portion("ui_dead_body")
	end
end
