--[[-----------------------------------------------------------------------------------------------
 File         : sa_init.script
 Description  : Модуль инициализации
 Copyright    : Shadows Addon
 Author       : Ray Twitty aka Shadows
 Date         : 13.11.2018
 Last edit    : 12.12.2018
--]]-----------------------------------------------------------------------------------------------
_G.effector_ids = {
	psy_effect = 3004,
	hit = 3007,
	snd_shock = 3014
}
---------------------------------------------------------------------------------------------------
_G.item_place = {
	undefined = 0,
	slot = 1,
	belt = 2,
	ruck = 3
}
---------------------------------------------------------------------------------------------------
_G.inventory_item_flags = {
	belt = 8
}
---------------------------------------------------------------------------------------------------
callback["drop_item_from_inventory"] = 129
callback["on_item_belt"] = 130
callback["on_item_ruck"] = 131
callback["on_item_slot"] = 132
callback["hit_effector"] = 144
callback["before_hit"] = 152
