--[[-----------------------------------------------------------------------------------------------
 File         : sa_init.script
 Description  : Модуль инициализации
 Copyright    : Shadows Addon
 Author       : Ray Twitty aka Shadows
 Date         : 13.11.2018
 Last edit    : 12.12.2018
--]]-----------------------------------------------------------------------------------------------
_G.effector_ids = {
	vampire_grasp = 3001,
	vampire_sucking = 3002,
	vampire_fade = 3003,
	psy_effect = 3004,
	head_shot = 3006,
	hit = 3007,
	yantar_blowout = 3009,
	yantar_underground_psi = 3010,
	shell_shock = 3011,
	earthquake = 3012,
	freeplay = 3013,
	radar_pass = 3014
}
---------------------------------------------------------------------------------------------------
_G.actor_flags = {
	sleep_state = false,
	bloodsucker_vampire_state = false
}
---------------------------------------------------------------------------------------------------
_G.key_events = {
	pressed = 0,
	released = 1
}
