local places = {
	["as"] = {
		sid =	9803,
		lv =	28719,
		gv =	1758,
		pos =	{ -317.23675537109,-26.327833175659,55.278633117676 },
		lvl =	"l07_military"
	},
	["as2"] = {
		sid =	9814,
		lv =	66343,
		gv =	1786,
		pos =	{ -274.62121582031,-27.297189712524,239.00979614258 },
		lvl =	"l07_military"
	},
	["as3"] = {
		sid =	9815,
		lv =	273147,
		gv =	1821,
		pos =	{ -33.368682861328,-20.897382736206,379.58074951172 },
		lvl =	"l07_military"
	},
	["as4"] = {
		sid =	9816,
		lv =	83694,
		gv =	1852,
		pos =	{ -243.89454650879,-0.28634393215179,435.28894042969 },
		lvl =	"l07_military"
	},
	["bunker"] = {
		sid =	9801,
		lv =	7807,
		gv =	2773,
		pos =	{ 8.3457946777344,-23.525426864624,19.003190994263 },
		lvl =	"l10u_bunker"
	},
	["svalka"] = {
		sid =	9802,
		lv =	127101,
		gv =	351,
		pos =	{ -77.325019836426,-3.660080909729,195.34251403809 },
		lvl =	"l02_garbage"
	},
	["svalka2"] = {
		sid =	9822,
		lv =	1201,
		gv =	260,
		pos =	{ -289.04534912109,-6.6783475875854,-178.82406616211 },
		lvl =	"l02_garbage"
	},
	["svalka3"] = {
		sid =	9823,
		lv =	344517,
		gv =	401,
		pos =	{ 200.77691650391,-0.638019323349,-145.20561218262 },
		lvl =	"l02_garbage"
	},
	["svalka4"] = {
		sid =	9861,
		lv =	284570,
		gv =	374,
		pos =	{ 122.61166381836,-4.2376079559326,153.47959899902 },
		lvl =	"l02_garbage"
	},
	["svalka5"] = {
		sid =	9862,
		lv =	324917,
		gv =	384,
		pos =	{ 173.82795715332,-0.30577194690704,51.149074554443 },
		lvl =	"l02_garbage"
	},
	["svalka6"] = {
		sid =	9863,
		lv =	311456,
		gv =	385,
		pos =	{ 97.819366455078,15.575645446777,31.107891082764 },
		lvl =	"l02_garbage"
	},
	["svalka7"] = {
		sid =	9864,
		lv =	166216,
		gv =	332,
		pos =	{ -49.738338470459,20.034204483032,115.88290405273 },
		lvl =	"l02_garbage"
	},
	["svalka8"] = {
		sid =	9865,
		lv =	2848,
		gv =	314,
		pos =	{ -277.18438720703,0.42264106869698,26.608871459961 },
		lvl =	"l02_garbage"
	},
	["svalka9"] = {
		sid =	9866,
		lv =	27161,
		gv =	308,
		pos =	{ -204.31503295898,0.77477610111237,-14.08620929718 },
		lvl =	"l02_garbage"
	},
	["svalka10"] = {
		sid =	9867,
		lv =	117566,
		gv =	299,
		pos =	{ -43.285057067871,22.38338470459,-109.06379699707 },
		lvl =	"l02_garbage"
	},
	["svalka11"] = {
		sid =	9868,
		lv =	123627,
		gv =	268,
		pos =	{ -82.571281433105,-2.6017231941223,-208.38046264648 },
		lvl =	"l02_garbage"
	},
	["svalka12"] = {
		sid =	9869,
		lv =	272734,
		gv =	263,
		pos =	{ 108.47253417969,-2.2334003448486,-264.66119384766 },
		lvl =	"l02_garbage"
	},
	["pripyat"] = {
		sid =	9804,
		lv =	260478,
		gv =	2219,
		pos =	{ 190.84159851074,2.8052725791931,212.05661010742 },
		lvl =	"l11_pripyat",
		info	= true
	},
	["pripyat2"] = {
		sid =	9820,
		lv =	7817,
		gv =	2216,
		pos =	{ -112.93630981445,2.8031325340271,97.108512878418 },
		lvl =	"l11_pripyat",
		info	= true
	},
	["x18"] = {
		sid =	9805,
		lv =	4086,
		gv =	1155,
		pos =	{ 5.0796270370483,-12.429841995239,15.65408706665 },
		lvl =	"l04u_labx18"
	},
	["td"] = {
		sid =	9824,
		lv =	212105,
		gv =	1025,
		pos =	{ 31.025503158569,-2.9186296463013,-18.474792480469 },
		lvl =	"l04_darkvalley"
	},
	["td2"] = {
		sid =	9825,
		lv =	377579,
		gv =	938,
		pos =	{ 177.20614624023,6.6501698493958,-368.2509765625 },
		lvl =	"l04_darkvalley"
	},
	["kordon"] = {
		sid =	9826,
		lv =	557888,
		gv =	245,
		pos =	{ 288.75579833984,6.6381821632385,334.9274597168 },
		lvl =	"l01_escape"
	},
	["kordon2"] = {
		sid =	9827,
		lv =	220208,
		gv =	16,
		pos =	{ -56.72008895874,-29.649417877197,-352.75286865234 },
		lvl =	"l01_escape"
	},
	["kordon3"] = {
		sid =	9848,
		lv =	314641,
		gv =	198,
		pos =	{ 33.526428222656,4.8442959785461,406.35510253906 },
		lvl =	"l01_escape"
	},
	["kordon4"] = {
		sid =	9849,
		lv =	326234,
		gv =	97,
		pos =	{ 43.707790374756,1.604367017746,157.83784484863 },
		lvl =	"l01_escape"
	},
	["kordon5"] = {
		sid =	9850,
		lv =	346954,
		gv =	97,
		pos =	{ 59.635650634766,19.672622680664,156.50126647949 },
		lvl =	"l01_escape"
	},
	["kordon6"] = {
		sid =	9851,
		lv =	479316,
		gv =	242,
		pos =	{ 176.90881347656,6.2265067100525,274.12582397461 },
		lvl =	"l01_escape"
	},
	["kordon7"] = {
		sid =	9852,
		lv =	418761,
		gv =	115,
		pos =	{ 116.21976470947,-7.5939545631409,-16.879535675049 },
		lvl =	"l01_escape"
	},
	["kordon8"] = {
		sid =	9853,
		lv =	71846,
		gv =	30,
		pos =	{ -178.17098999023,-29.790063858032,-355.4208984375 },
		lvl =	"l01_escape"
	},
	["kordon9"] = {
		sid =	9854,
		lv =	116591,
		gv =	19,
		pos =	{ -138.1682434082,-25.440311431885,-356.09561157227 },
		lvl =	"l01_escape"
	},
	["kordon10"] = {
		sid =	9855,
		lv =	46406,
		gv =	38,
		pos =	{ -206.31811523438,-36.486312866211,-275.36505126953 },
		lvl =	"l01_escape"
	},
	["kordon11"] = {
		sid =	9856,
		lv =	34087,
		gv =	47,
		pos =	{ -218.33445739746,-19.930738449097,-167.60050964355 },
		lvl =	"l01_escape"
	},
	["kordon12"] = {
		sid =	9857,
		lv =	45951,
		gv =	58,
		pos =	{ -207.27334594727,-22.535316467285,-128.54507446289 },
		lvl =	"l01_escape"
	},
	["kordon13"] = {
		sid =	9858,
		lv =	11502,
		gv =	67,
		pos =	{ -246.82745361328,-14.313711166382,-17.025833129883 },
		lvl =	"l01_escape"
	},
	["kordon14"] = {
		sid =	9859,
		lv =	143574,
		gv =	73,
		pos =	{ -112.90689849854,-8.191520690918,7.4986095428467 },
		lvl =	"l01_escape"
	},
	["kordon15"] = {
		sid =	9860,
		lv =	18736,
		gv =	47,
		pos =	{ -241.71829223633,-16.903062820435,-155.92127990723 },
		lvl =	"l01_escape"
	},
	["radar"] = {
		sid =	9806,
		lv =	93230,
		gv =	2081,
		pos =	{ 351.03564453125,-45.688995361328,-201.36804199219 },
		lvl =	"l10_radar"
	},
	["radar2"] = {
		sid =	9811,
		lv =	67978,
		gv =	1930,
		pos =	{ 304.68270874023,-39.390411376953,-25.789834976196 },
		lvl =	"l10_radar"
	},
	["radar3"] = {
		sid =	9812,
		lv =	14611,
		gv =	2013,
		pos =	{ 14.053562164307,-1.2424700260162,41.381050109863 },
		lvl =	"l10_radar"
	},
	["radar4"] = {
		sid =	9813,
		lv =	6439,
		gv =	1960,
		pos =	{ -12.000325202942,0.37741497159004,-67.812171936035 },
		lvl =	"l10_radar",
		info	= true
	},
	["undergraund"] = {
		sid =	9810,
		lv =	2505,
		gv =	745,
		pos =	{ -84.987205505371,-16.462963104248,-60.738975524902 },
		lvl =	"l03u_agr_underground"
	},
	["bar"] = {
		sid =	9821,
		lv =	45474,
		gv =	1188,
		pos =	{ 193.61143493652,0.097166806459427,71.526657104492 },
		lvl =	"l05_bar"
	},
	["bar2"] = {
		sid =	9842,
		lv =	39883,
		gv =	1204,
		pos =	{ 175.31533813477,-0.0002819299697876,145.91943359375 },
		lvl =	"l05_bar"
	},
	["bar3"] = {
		sid =	9843,
		lv =	47206,
		gv =	1270,
		pos =	{ 198.24176025391,3.271665096283,-77.252685546875 },
		lvl =	"l05_bar"
	},
	["bar4"] = {
		sid =	9844,
		lv =	59366,
		gv =	1277,
		pos =	{ 232.64491271973,5.1447978019714,-113.61502838135 },
		lvl =	"l05_bar"
	},
	["bar5"] = {
		sid =	9845,
		lv =	68763,
		gv =	1274,
		pos =	{ 276.64755249023,0.055086404085159,-66.742523193359 },
		lvl =	"l05_bar"
	},
	["bar6"] = {
		sid =	9846,
		lv =	35860,
		gv =	1238,
		pos =	{ 128.80438232422,-4.8249382972717,16.76756477356 },
		lvl =	"l05_bar"
	},
	["bar7"] = {
		sid =	9847,
		lv =	33903,
		gv =	1239,
		pos =	{ 116.09830474854,-5.3052234649658,12.649393081665 },
		lvl =	"l05_bar"
	},
	["agroprom"] = {
		sid =	9828,
		lv =	428448,
		gv =	498,
		pos =	{ 253.95002746582,-0.20055566728115,76.619018554688 },
		lvl =	"l03_agroprom"
	},
	["agroprom2"] = {
		sid =	9829,
		lv =	117939,
		gv =	523,
		pos =	{ -122.60626983643,10.350003242493,164.23361206055 },
		lvl =	"l03_agroprom"
	},
	["agroprom3"] = {
		sid =	9830,
		lv =	103987,
		gv =	621,
		pos =	{ -135.0357208252,4.9933753013611,-196.9232635498 },
		lvl =	"l03_agroprom"
	},
	["yantar1"] = {
		sid =	9831,
		lv =	6635,
		gv =	1486,
		pos =	{ -98.555587768555,-12.03422164917,-263.20428466797 },
		lvl =	"l08_yantar"
	},
	["yantar2"] = {
		sid =	9832,
		lv =	22009,
		gv =	1454,
		pos =	{ -49.516319274902,-12.687213897705,-263.55654907227 },
		lvl =	"l08_yantar"
	},
	["yantar3"] = {
		sid =	9833,
		lv =	85543,
		gv =	1440,
		pos =	{ 87.165092468262,1.5326626300812,-137.15473937988 },
		lvl =	"l08_yantar"
	},
	["yantar4"] = {
		sid =	9834,
		lv =	98895,
		gv =	1520,
		pos =	{ 110.79859924316,0.51710104942322,67.085777282715 },
		lvl =	"l08_yantar"
	},
	["yantar5"] = {
		sid =	9835,
		lv =	93237,
		gv =	1515,
		pos =	{ 102.05886077881,-0.055661827325821,-38.264953613281 },
		lvl =	"l08_yantar"
	},
	["yantar6"] = {
		sid =	9836,
		lv =	50739,
		gv =	1505,
		pos =	{ 23.551870346069,-3.417268037796,-50.092147827148 },
		lvl =	"l08_yantar"
	},
	["yantar7"] = {
		sid =	9837,
		lv =	57034,
		gv =	1445,
		pos =	{ 35.566432952881,0.036594957113266,19.930288314819 },
		lvl =	"l08_yantar"
	},
	["yantar8"] = {
		sid =	9838,
		lv =	87168,
		gv =	1514,
		pos =	{ 90.726051330566,0.028770864009857,-2.0428421497345 },
		lvl =	"l08_yantar"
	},
	["yantar9"] = {
		sid =	9839,
		lv =	38250,
		gv =	1525,
		pos =	{ -2.272828578949,0.31553617119789,-12.611492156982 },
		lvl =	"l08_yantar"
	},
	["yantar10"] = {
		sid =	9840,
		lv =	39736,
		gv =	1525,
		pos =	{ 0.41521853208542,20.732145309448,-11.2778673172 },
		lvl =	"l08_yantar"
	},
	["yantar11"] = {
		sid =	9841,
		lv =	53157,
		gv =	1480,
		pos =	{ 28.687835693359,-5.943422794342,-272.9033203125 },
		lvl =	"l08_yantar"
	},
	["dt1"] = {
		sid =	9870,
		lv =	15216,
		gv =	1391,
		pos =	{ -236.99816894531,9.3585262298584,56.257476806641 },
		lvl =	"l06_rostok"
	},
	["dt2"] = {
		sid =	9871,
		lv =	8119,
		gv =	1382,
		pos =	{ -254.47462463379,-5.8917918205261,88.748420715332 },
		lvl =	"l06_rostok"
	},
	["dt3"] = {
		sid =	9872,
		lv =	4658,
		gv =	1379,
		pos =	{ -268.44509887695,-6.0012273788452,106.45835113525 },
		lvl =	"l06_rostok"
	},
	["dt4"] = {
		sid =	9873,
		lv =	7269,
		gv =	1338,
		pos =	{ -282.68493652344,-0.0055593848228455,203.75721740723 },
		lvl =	"l06_rostok"
	},
	["dt5"] = {
		sid =	9874,
		lv =	32043,
		gv =	1329,
		pos =	{ -173.43870544434,-0.0011672079563141,192.25354003906 },
		lvl =	"l06_rostok"
	},
	["dt6"] = {
		sid =	9875,
		lv =	38957,
		gv =	1328,
		pos =	{ -149.55770874023,0.096051603555679,179.93653869629 },
		lvl =	"l06_rostok"
	},
	["dt7"] = {
		sid =	9876,
		lv =	22437,
		gv =	1370,
		pos =	{ -217.82315063477,1.935809969902,88.06103515625 },
		lvl =	"l06_rostok"
	},
	["dt8"] = {
		sid =	9877,
		lv =	32382,
		gv =	1322,
		pos =	{ -169.39688110352,-0.0033434927463531,82.040466308594 },
		lvl =	"l06_rostok"
	},
	["dt9"] = {
		sid =	9878,
		lv =	36070,
		gv =	1321,
		pos =	{ -159.36485290527,-0.0026704967021942,99.839752197266 },
		lvl =	"l06_rostok"
	},
	["dt11"] = {
		sid =	9880,
		lv =	46578,
		gv =	1421,
		pos =	{ -89.581573486328,3.1074571609497,148.33610534668 },
		lvl =	"l06_rostok"
	},
	["to_sarcofag"] = {
		sid =	8377,
		lv =	6321,
		gv =	2417,
		pos =	{ 69.901214599609,67.818977355957,19.644428253174 },
		lvl =	"l12u_sarcofag"
	}
}

function create_level_changer(
	p_story_id,	-- STORY_ID нового level_changer (понадобитс€ нам позже)
	p_position,	-- вектор, координаты точки, в которой будет располагатьс€ центр нового level_changer
	p_lvertex_id,	-- level_vertext_id  - идентифицируют уровень, на котором будет создан level_changer
	p_gvertex_id,	-- game_vertext_id

	p_dest_lv,	-- level_vertex_id   - идентифицируют уровень, на который level_changer будет перебрасывать игрока
	p_dest_gv,	-- game_vertex_id
	p_dest_pos,	-- координаты точки, в которой на новом уровне окажетс€ игрок
	p_dest_dir,	-- направрение взгл€да игрока
	p_dest_level,	-- название уровн€, например "L11_Pripyat"
	p_silent	-- следует задать 1, чтобы подавить вопрос о смене уровн€ (автоматический переход)
)
	local obj = AI:create("level_changer", p_position, p_lvertex_id, p_gvertex_id)

	local packet = net_packet()
	obj:STATE_Write(packet)

	-- свойства cse_alife_object
	local game_vertex_id 			= packet:r_u16()
	local cse_alife_object__unk1_f32 	= packet:r_float()
	local cse_alife_object__unk2_u32 	= packet:r_u32()
	local level_vertex_id 			= packet:r_u32()
	local object_flags 			= packet:r_u32()
	local custom_data 			= packet:r_stringZ()
	local story_id 				= packet:r_u32()
	local spawn_story_id			= packet:r_u32()

	-- свойства cse_shape
	local shape_count 			= packet:r_u8()
	for i=1,shape_count do
		local shape_type 		= packet:r_u8()
		if shape_type == 0 then
			-- sphere
			local center 		= packet:r_vec3()
			local radius 		= packet:r_float()
		else
			-- box
			local axis_x_x = packet:r_float()
			local axis_x_y = packet:r_float()
			local axis_x_z = packet:r_float()
			local axis_y_x = packet:r_float()
			local axis_y_y = packet:r_float()
			local axis_y_z = packet:r_float()
			local axis_z_x = packet:r_float()
			local axis_z_y = packet:r_float()
			local axis_z_z = packet:r_float()
			local offset_x = packet:r_float()
			local offset_y = packet:r_float()
			local offset_z = packet:r_float()
		end
	end

	-- свойства cse_alife_space_restrictor
	local restrictor_type 			= packet:r_u8()

	-- свойства cse_level_changer
	local dest_game_vertex_id		= packet:r_u16()
	local dest_level_vertex_id 		= packet:r_u32()
	local dest_position 			= packet:r_vec3()
	local dest_direction 			= packet:r_vec3()
	local dest_level_name 			= packet:r_stringZ()
	local dest_graph_point 			= packet:r_stringZ()
	local silent_mode 			= packet:r_u8()

	packet:w_begin(game_vertex_id)			-- game_vertex_id
	packet:w_float(cse_alife_object__unk1_f32)
	packet:w_u32(cse_alife_object__unk2_u32)
	packet:w_u32(level_vertex_id)			-- level_vertex_id
	packet:w_u32( bit_not(193) )			-- object_flags = -193 = 0xFFFFFF3E
	packet:w_stringZ(custom_data)
	packet:w_u32(p_story_id)			-- story_id
	packet:w_u32(spawn_story_id)

	packet:w_u8(1)			-- количество фигур
	packet:w_u8(1)			-- тип фигуры: box
	packet:w_float(2)	   -- axis_x_x
	packet:w_float(0)	   -- axis_x_y
	packet:w_float(0)	   -- axis_x_z
	packet:w_float(0)	   -- axis_y_x
	packet:w_float(4)	   -- axis_y_y
	packet:w_float(0)	   -- axis_y_z
	packet:w_float(0)	   -- axis_z_x
	packet:w_float(0)	   -- axis_z_y
	packet:w_float(4)	   -- axis_z_z
	packet:w_float(0)	   -- offset_x
	packet:w_float(0)	   -- offset_y
	packet:w_float(0)          -- offset_z

	packet:w_u8(3)	 	   -- restrictor_type

	packet:w_u16(p_dest_gv)			-- destination game_vertex_id
	packet:w_s32(p_dest_lv)			-- destination level_vertex_id
	packet:w_vec3(p_dest_pos)		-- destination position
	packet:w_vec3(p_dest_dir)		-- destination direction (направление взгл€да)
	packet:w_stringZ(p_dest_level)		-- destination level name
	packet:w_stringZ("start_actor_02")	-- some string, always const
	packet:w_u8(p_silent)			-- 1 for silent level changing

	packet:r_seek(0)
	obj:STATE_Read(packet, packet:w_tell())
 level.add_pp_effector ("teleport.ppe", 2006, false)

end

function jump(where)
	local place = places[where]

	if place.info then
		give_info("exit_" .. where)
	end
	create_level_changer(place.sid, Actor:position(), Actor:level_vertex_id(),
			     Actor:game_vertex_id(), place.lv, place.gv,
			     vector():set(unpack(place.pos)), xyz(), place.lvl, 1)
end

-- таблица телепортов
-- art - требуемый арт дл€ телепортации (если задан - отберЄтс€ у √√)
-- keep - оставл€ть ли телепорт
-- goto_func - список вариантов заброски телепортом
local teleports = {
	device_teleport = {
		art = "af_electra_moonlight",
		goto_func = {
			"agroprom",
			"agroprom2",
			"agroprom3",
			"as",
			"as2",
			"as3",
			"as4",
			"bar",
			"bar2",
			"bar3",
			"bar4",
			"bar5",
			"bar6",
			"bar7",
			"bunker",
			"dt1",
			"dt2",
			"dt3",
			"dt4",
			"dt5",
			"dt6",
			"dt7",
			"dt8",
			"dt9",
			"dt10",
			"dt11",
			"kordon",
			"kordon2",
			"kordon3",
			"kordon4",
			"kordon5",
			"kordon6",
			"kordon7",
			"kordon8",
			"kordon9",
			"kordon10",
			"kordon11",
			"kordon12",
			"kordon13",
			"kordon14",
			"kordon15",
			"pripyat",
			"pripyat2",
			"radar",
			"radar2",
			"radar3",
			"radar4",
			"svalka",
			"svalka2",
			"svalka3",
			"svalka4",
			"svalka5",
			"svalka6",
			"svalka7",
			"svalka8",
			"svalka9",
			"svalka10",
			"svalka11",
			"svalka12",
			"td",
			"td2",
			"undergraund",
			"x18",
			"yantar1",
			"yantar2",
			"yantar3",
			"yantar4",
			"yantar5",
			"yantar6",
			"yantar7",
			"yantar8",
			"yantar9",
			"yantar10",
			"yantar11"
		}
	},
	science_teleport3 = {
		art = "af_electra_moonlight",
		goto_func = {
			"yantar1",
			"yantar2",
			"yantar3",
			"yantar4",
			"yantar5",
			"yantar6",
			"yantar7",
			"yantar8",
			"yantar9",
			"yantar10",
			"yantar11"
		}
	},
	science_teleport2 = {
		art = "af_electra_moonlight",
		goto_func = {
			"bar",
			"bar2",
			"bar3",
			"bar4",
			"bar5",
			"bar6",
			"bar7"
		}
	},
	science_teleport = {
		art = "af_electra_moonlight",
		goto_func = {
			"kordon",
			"kordon2",
			"kordon3",
			"kordon4",
			"kordon5",
			"kordon6",
			"kordon7",
			"kordon8",
			"kordon9",
			"kordon10",
			"kordon11",
			"kordon12",
			"kordon13",
			"kordon14",
			"kordon15"
		}
	}
}

function teleport_start(obj)
	local sect = obj:section()
	local teleport = teleports[sect]
	if not teleport then return end

	-- отбираем арт у √√, если нужно отобрать
	if teleport.art then
		local art = Actor:object(teleport.art)
		if art then
			release(art)
		else
			amk.spawn_item_in_inv(sect)
			return
		end
	end

	-- вызываем случайную функцию дл€ данного телепорта
	jump(table.random(teleport.goto_func))

	if teleport.keep then -- вернуть телепорт в рюкзак
		amk.spawn_item_in_inv(sect)
	end
end

function remove_old_teleport()
	local se_obj
	for nam, tbl in pairs(places) do
		se_obj = AI:story_object(tbl.sid)
		if se_obj then
			AI:release(se_obj, true)
		end
	end
end
