----------------------------------------------------------------------------------------------------
-- Disable actor's weapon
----------------------------------------------------------------------------------------------------

class "action_no_weapon"

function action_no_weapon:__init( obj, storage )
	self.object = obj
	self.st = storage
end

function action_no_weapon:reset_scheme()
end

function action_no_weapon:update( delta )
	xr_logic.try_switch_to_another_section( self.object, self.st, db_actor )
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder_q(npc, storage)
	storage.actions[ action_no_weapon(npc, storage) ] = true
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
end
