--/amk_rel_1/
-- инициализация
class "cheat" (CUIScriptWnd)

function cheat:__init(owner) super()
	self.owner = owner
	self:InitControls()
	self:InitCallBacks()
end

function cheat:__finalize() end

function cheat:InitControls()
	-- здесь определяем координаты левого верхнего угла и ширину-высоту
	self:Init(50,50,550,450)

	-- файл-описатель наших элементов
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_cheat_wnd.xml")

	-- видео на заднем плане
	xml:InitStatic("back_video", self)

	-- рамка
	xml:InitStatic("background", self)

	-- кнопки
	self:Register(xml:Init3tButton("caption", self),"caption")
	self:Register(xml:Init3tButton("btn_1", self),"btn_1")
	self:Register(xml:Init3tButton("btn_2", self),"btn_2")
	self:Register(xml:Init3tButton("btn_3", self),"btn_3")
	if Actor.health < 0.9 then
		self:Register(xml:Init3tButton("btn_4", self),"btn_4")
	end
	-- кнопка выхода
	self:Register(xml:Init3tButton("btn_quit", self),"btn_quit")
end

function cheat:InitCallBacks()
	-- тут интерактивные элементы, при определенном действии выполняется заданная ф-ия
	self:Connect("btn_1", ui_events.BUTTON_CLICKED, self.cheat1)
	self:Connect("btn_2", ui_events.BUTTON_CLICKED, self.cheat2)
	self:Connect("btn_3", ui_events.BUTTON_CLICKED, self.cheat3)
	if Actor.health < 0.9 then
		self:Connect("btn_4", ui_events.BUTTON_CLICKED, self.cheat4)
	end
	self:Connect("btn_quit", ui_events.BUTTON_CLICKED, self.on_quit)
end

function cheat:on_quit()
 self:GetHolder():start_stop_menu (self,true)
end

function cheat:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
-- на выход повесим Esc
		if dik == DIK_keys.DIK_ESCAPE then
			self:on_quit()
		end
		if dik == DIK_keys.DIK_NUMPAD1 then
			self:cheat1()
		end
		if dik == DIK_keys.DIK_NUMPAD2 then
			self:cheat2()
		end
		if dik == DIK_keys.DIK_NUMPAD3 then
			self:cheat3()
		end
		if dik == DIK_keys.DIK_NUMPAD4 then
			self:cheat4()
		end
	end
	return true
end

function cheat:cheat1()
		Dream:sleep(3)
		self:on_quit()
end
function cheat:cheat2()
		Dream:sleep(5)
		self:on_quit()
end
function cheat:cheat3()
		Dream:sleep(8)
		self:on_quit()
end
function cheat:cheat4()
		Dream:sleep()
		self:on_quit()
end

function cheat:on_quit()
	self:GetHolder():start_stop_menu (self,true)
end

